---
name: Sami Amer
description: ''
logo: assets/images/signature.png
favicon: assets/images/favicon.ico
email: ''
mailchimp-list: ''
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-menus
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  sami:
    name: Sami Amer
    site: www.sami.ps
    avatar: "/assets/images/sami_profile.jpg"
    bio: ''
    email: zero.beefier.0r@icloud.com
    twitter: https://twitter.com/Sami_Amer_PS
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: sami
    avatar: "/assets/images/sami_profile.jpg"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
# Google Analytics
google_analytics: G-W0YBFRWLY7
